name: build WSL4Redroid

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'WSL2 Kernel Version'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential flex bison dwarves libssl-dev libelf-dev cpio qemu-utils git

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare kernel version to build
      run: |
        git clone https://github.com/microsoft/WSL2-Linux-Kernel.git

        pushd WSL2-Linux-Kernel
        INPUT_TAG="${{ github.event.inputs.tag }}"
        if [ -n "${INPUT_TAG}" ] && git tag -l "${INPUT_TAG}" | grep -q "${INPUT_TAG}"; then
          echo "Using input tag: ${INPUT_TAG}"
          echo "KERNEL_TAG=${INPUT_TAG}" >> ${GITHUB_ENV}
        else
          echo "Input tag is invalid or empty. Using latest tag instead."
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "KERNEL_TAG=${LATEST_TAG}" >> ${GITHUB_ENV}
        fi
        popd

        mv WSL2-Linux-Kernel WSL2-Linux-Kernel.tmp

    - name: Restore cached build
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: WSL2-Linux-Kernel
        key: kernel-${{ env.KERNEL_TAG }}

    - name: Clone kernel repository
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: |
        mv WSL2-Linux-Kernel.tmp WSL2-Linux-Kernel
        cd WSL2-Linux-Kernel
        git checkout ${{ env.KERNEL_TAG }}

    - name: Prepare kernel config
      run: |
        rm -rf WSL2-Linux-Kernel.tmp
        cd WSL2-Linux-Kernel
        echo "Build commit"
        git log -1

        cp Microsoft/config-wsl .config
        yes "" | make olddefconfig

        echo "Merging additional config from wsl.kernel/redroid.conf..."
        scripts/kconfig/merge_config.sh -m .config ${GITHUB_WORKSPACE}/wsl.kernel/redroid.conf

        echo "Finalizing config..."
        yes "" | make olddefconfig

    - name: Build kernel
      run: |
        cd WSL2-Linux-Kernel

        make -j$(nproc)
        make INSTALL_MOD_PATH="$PWD/modules" modules_install

        rm -rf zzzTarget
        find ./modules -name '*.ko' -exec strip --strip-unneeded {} +
        sudo ./Microsoft/scripts/gen_modules_vhdx.sh "$PWD/modules" $(make -s kernelrelease) zzzTarget/modules.vhdx
        mv arch/x86_64/boot/bzImage zzzTarget
        rm -rf modules

    - name: Upload built kernel
      uses: actions/upload-artifact@v4
      with:
        name: wsl-kernel-${{ env.KERNEL_TAG }}
        path: zzzTarget

    - name: Update build cache
      uses: actions/cache/save@v4
      with:
        path: WSL2-Linux-Kernel
        key: kernel-${{ env.KERNEL_TAG }}

